services:
  - type: web
    name: transformer-model-frontend
    env: node
    rootDir: frontend
    buildCommand: |
      cd frontend
      npm install
      npm audit fix --force
      npm run build
    startCommand: |
      cd frontend
      npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_API_URL
        value: https://transformer-model-backend.onrender.com
      - key: NODE_VERSION
        value: 20.11.1
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true 