services:
  - type: web
    name: transformer-model-frontend
    env: node
    buildCommand: |
      npm install
      npm audit fix --force
      npm run build
    startCommand: serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://transformer-model-backend.onrender.com
      - key: NODE_VERSION
        value: 20.11.1
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true 